### ISSUE TITLE
Cannot send msg after installing character maker

### ISSUE THREAD

**Issue by Loup-Garou911XD** [bombsquad-community/plugin-manager#54]
Cannot send msg in advance_party_window or ultra_party_window after installing character maker

**Comment by rikkolovescats** [comment]
Can you also post the error here if any. Happy to accept PRs!

**Comment by Loup-Garou911XD** [comment]
> Can you also post the error here if any. Happy to accept PRs!

On mobile so can't send errors

**Comment by Loup-Garou911XD** [comment]
```BombSquad 1.7.9 build 20879.
Using OpenGL ES 3 (vendor: Imagination Technologies, renderer: PowerVR Rogue GE8320, version: OpenGL ES 3.2 build 1.11@5425693)
Exception in Python call:
  root call: <function make_sys at 0xbc2536e8>
  root call origin: Terminal.py:175
  context: <UI Context>
  real-time: 6532
  sim-time: <unavailable>
  base-time: <unavailable>
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/Terminal.py", line 106, in make_sys
    ba.modutils.create_user_system_scripts()
AttributeError: module 'ba' has no attribute 'modutils'
Exception in Python call:
  root call: <bound method ModifiedPartyWindow._send_chat_message of <advanced_party_window.ModifiedPartyWindow object at 0xb97baaa8>>
  root call origin: colorscheme.py:100
  context: <UI Context>
  real-time: 14711
  sim-time: <unavailable>
  base-time: <unavailable>
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/advanced_party_window.py", line 995, in _send_chat_message
    _ba.chatmessage(msg)
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/floater.py", line 262, in new_chat_message
    old_fcm(msg, clients, sender_override)
TypeError: _new_chatmessage() takes 1 positional argument but 3 were given
Exception in Python call:
  root call: <bound method ModifiedPartyWindow._send_chat_message of <advanced_party_window.ModifiedPartyWindow object at 0xb97baaa8>>
  root call origin: colorscheme.py:100
  context: <UI Context>
  real-time: 15024
  sim-time: <unavailable>
  base-time: <unavailable>
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/advanced_party_window.py", line 995, in _send_chat_message
    _ba.chatmessage(msg)
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/floater.py", line 262, in new_chat_message
    old_fcm(msg, clients, sender_override)
TypeError: _new_chatmessage() takes 1 positional argument but 3 were given
Exception in Python call:
  root call: <bound method ModifiedPartyWindow._send_chat_message of <advanced_party_window.ModifiedPartyWindow object at 0xb97baaa8>>
  root call origin: colorscheme.py:100
  context: <UI Context>
  real-time: 15206
  sim-time: <unavailable>
  base-time: <unavailable>
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/advanced_party_window.py", line 995, in _send_chat_message
    _ba.chatmessage(msg)
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/floater.py", line 262, in new_chat_message
    old_fcm(msg, clients, sender_override)
TypeError: _new_chatmessage() takes 1 positional argument but 3 were given
Exception in Python call:
  root call: <bound method ModifiedPartyWindow._send_chat_message of <advanced_party_window.ModifiedPartyWindow object at 0xb97baaa8>>
  root call origin: colorscheme.py:100
  context: <UI Context>
  real-time: 15321
  sim-time: <unavailable>
  base-time: <unavailable>
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/advanced_party_window.py", line 995, in _send_chat_message
    _ba.chatmessage(msg)
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/floater.py", line 262, in new_chat_message
    old_fcm(msg, clients, sender_override)
TypeError: _new_chatmessage() takes 1 positional argument but 3 were given
```

After installing terminal,this was the output
